/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConfirmModal: typeof import('./src/components/AppConfirmModal.vue')['default']
    AuthModal: typeof import('./src/components/AuthModal.vue')['default']
    EditorSidebarItem: typeof import('./src/components/editor/EditorSidebarItem.vue')['default']
    EditorTextField: typeof import('./src/components/editor/EditorTextField.vue')['default']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FeedbackModal: typeof import('./src/components/FeedbackModal.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
